### PR TITLE
do not rely on redirect fetch rpm with suffix instead

### PR DESCRIPTION
**Pull request by lkocman**
* Fixes Issue #15

### CODE REVIEW

**Comment by lkocman** [comment]
Let's keep this open, there might be other issues. But this could in theory be the root cause of #Issue 15.

**Comment by lkocman** [comment]
Full run with set -x FYI https://paste.opensuse.org/19749822

**Review by sknorr — COMMENTED** [review]
If this works, it's fine by me. I have never actually touched that script all too much, making this review a not so super-qualified one.

**Comment by sknorr** [comment]
Manually merged as 5407a503.

**Pull request closed without merging**
